- name: Deploy Docker application
  hosts: all
  become: yes
  vars:
    docker_image: "nkattin/antibodybind:latest"

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image
      command: docker pull {{ docker_image }}

    - name: Stop existing container
      command: docker stop antibodybind || true

    - name: Remove existing container
      command: docker rm antibodybind || true

    - name: Run new container
      command: docker run -d --name antibodybind -p 8000:8000 {{ docker_image }}